### ISSUE TITLE
`onvif-util -u admin -p '' 192.168.1.10` command `get network` crashes with SIGSEGV

### ISSUE THREAD

**Issue by reivilibre** [sr99622/libonvif#71]
Hi,

I'm using v1.4.4 as tagged (whilst packaging it myself for NixOS) and `onvif-util` is crashing with a SIGSEGV when I run `onvif-util -u admin -p '' 192.168.1.10` and type the command `get network`.

The backtrace of the crash is:
```
(gdb) bt
#0  0x00007ffff7faf3af in addHttpHeader (doc=doc@entry=0x423e90, root=root@entry=0x424890, xaddrs=xaddrs@entry=0x422240 "", post_type=post_type@entry=0x4211bc "", cmd=cmd@entry=0x7ffffffede80 "", 
    cmd_length=cmd_length@entry=4096) at /build/source/libonvif/src/onvif.c:2128
#1  0x00007ffff7fb788a in getProfileToken (onvif_data=0x41feb0, profileIndex=0) at /build/source/libonvif/src/onvif.c:1368
#2  0x0000000000403c82 in profileCheck (onvif_data=onvif_data@entry=0x41feb0, args=...) at /build/source/onvif-util/src/onvif-util.cpp:169
#3  0x0000000000405449 in main (argc=<optimized out>, argv=<optimized out>) at /build/source/onvif-util/src/onvif-util.cpp:400
```

Locals:
```
(gdb) info locals
outputbuffer = <optimized out>
size = 929
xml = "<SOAP-ENV:Envelope xmlns:SOAP-ENV=\"http://www.w3.org/2003/05/soap-envelope\" xmlns:trt=\"http://www.onvif.org/ver10/media/wsdl\" xmlns:wsse=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecu"...
c_xml_size = "929\000\000"
xml_size_length = 4
tmp = '\000' <repeats 127 times>
mark = <optimized out>
start = -4334142
tmp_len = 0
j = 0
end = <optimized out>
tmp2 = '\000' <repeats 127 times>
host = '\000' <repeats 127 times>
port_buf = '\000' <repeats 127 times>
port = <optimized out>
content = '\000' <repeats 130 times>
content_length = '\000' <repeats 18 times>
http_terminate = "\000\000\000\000"
p = <optimized out>
h = <optimized out>
c = 131
cl = 19
cmd_size = <optimized out>
i = <optimized out>
s = <optimized out>
```

The XML it was processing:
```
(gdb) print -elements 3000 -- xml
$2 = "<SOAP-ENV:Envelope xmlns:SOAP-ENV=\"http://www.w3.org/2003/05/soap-envelope\" xmlns:trt=\"http://www.onvif.org/ver10/media/wsdl\" xmlns:wsse=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd\" xmlns:wsu=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd\"><SOAP-ENV:Header><wsse:Security SOAP-ENV:mustUnderstand=\"1\"><wsse:UsernameToken><wsse:Username></wsse:Username><wsse:Password Type=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordDigest\">XCLO5rjs6+ngg/F/x19eaqtOA2w=</wsse:Password><wsse:Nonce EncodingType=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary\">zVpzwc5udVRzhLq0SlxzKHLiJUw=</wsse:Nonce><wsu:Created>2023-10-30T22:10:51.620Z</wsu:Created></wsse:UsernameToken></wsse:Security></SOAP-ENV:Header><SOAP-ENV:Body><trt:GetProfiles/></SOAP-ENV:Body></SOAP-ENV:Envelope>", '\000'
```

Please let me know if there's any more useful info I can get for you.

I have a packet capture from a different (but same command / same crash) run, using Wireshark: [onvif-util_packets.zip](https://github.com/sr99622/libonvif/files/13210268/onvif-util_packets.zip)

(The camera is a cheap generic camera so it wouldn't surprise me if this isn't your code's fault...)

**Comment by sr99622** [comment]
Looking at the trace, the point of failure seems to be line 2128 in onvif.c which is in the code block

```
2122    char tmp[128] = {0};
2123    char * mark = strstr(xaddrs, "//");
2124    int start = mark-xaddrs+2;
2125    int tmp_len = strlen(xaddrs);
2126    int j;
2127    for (j=0; j<tmp_len-start; j++) {
2128        tmp[j] = xaddrs[j+start];
2129    }
2130    tmp[j] = '\0';
```

This is where libonvif is preparing an http style header to send to the camera as a command sequence that includes the address of the camera and the command itself.  The code is very primitive and quite ancient, so there are a few things that have been left vulnerable to malformed input.  If this is indeed the actual point of failure, it is reasonable to conclude that the camera xaddrs is malformed and a buffer overrun is occurring, causing the sigsev fault.

One obvious thing to test is that the substring search for the "//" character sequence is successful by checking for null pointer returned from the strstr function in line 2123.  Unfortunately, this isn't going to do much good other than preventing the onvif-util program from crashing, as that string parse is necessary for communicating with the camera.

It's hard to know what the root cause of the issue is without having the actual camera in hard, as the problem may be originating further up the chain of events.  Frankly, I would be surprised if onvif-util is able to work with the camera at all if the problem is indeed caused by a malformed xaddrs from the camera as this is a fundamental parameter needed by onvif.

Something else worth looking at it the use of the camera without a password.  This is a scenario that was not well tested during development.  If you are able to assign a password to the camera and test that successfully, that would indicate the code is indeed the problem and is not handling the zero length password properly.
