### ISSUE TITLE
AttributeError: module 'avio' has no attribute 'Player'

### ISSUE THREAD

**Issue by genevera** [sr99622/libonvif#91]
This is on Mac whether I build or just install.  Any ideas to get this to compile such that it runs correctly would be appreciated.  Full output below:

```bash
⏚ [genevera:~/src/libonvif/onvif-gui ⚞15] [onvif] [3.1.2] master(+0/-0) ± onvif-gui; python --version
Traceback (most recent call last):
  File "/Users/genevera/.pyenv/versions/miniconda3-latest/envs/onvif/bin/onvif-gui", line 5, in <module>
    from gui.main import run
  File "/Users/genevera/.pyenv/versions/miniconda3-latest/envs/onvif/lib/python3.12/site-packages/gui/__init__.py", line 1, in <module>
    from .main import MainWindow
  File "/Users/genevera/.pyenv/versions/miniconda3-latest/envs/onvif/lib/python3.12/site-packages/gui/main.py", line 61, in <module>
    class Player(avio.Player):
                 ^^^^^^^^^^^
AttributeError: module 'avio' has no attribute 'Player'
Python 3.12.3
```

Same error on 3.10 or 3.12:

```bash
⌁43% [genevera:~/src/libonvif/onvif-gui ⚞15] [onvif310] [3.1.2] master(+0/-0) 1 ± onvif-gui; python --version
Traceback (most recent call last):
  File "/Users/genevera/.pyenv/versions/miniconda3-latest/envs/onvif310/bin/onvif-gui", line 5, in <module>
    from gui.main import run
  File "/Users/genevera/.pyenv/versions/miniconda3-latest/envs/onvif310/lib/python3.10/site-packages/gui/__init__.py", line 1, in <module>
    from .main import MainWindow
  File "/Users/genevera/.pyenv/versions/miniconda3-latest/envs/onvif310/lib/python3.10/site-packages/gui/main.py", line 61, in <module>
    class Player(avio.Player):
AttributeError: module 'avio' has no attribute 'Player'
Python 3.10.14
```

**Comment by sr99622** [comment]
Thank you so much for reaching out, this is something I am working on to
get version 7 on mac. The feedback from users is very important so, always
glad to hear about your experience. Please let me know how things are going
if you have any questions.
